# Generated by Django 4.2 on 2024-04-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='app1.userprofile'),
        ),
    ]
